### ISSUE TITLE
Provider for Taiwan

### ISSUE THREAD

**Issue by Dagolin** [azuyalabs/yasumi#157]
Yes, Taiwan is just one of the countries have NO arithmetic calendar, so it's impossible to implement a once and for all solution for them, even the government themselves cannot tell. 

However it's possible to fetch the date on the fly from the government, normally the government will announce the holidays a year before, Taiwan for example, the government announces the calendar of next year on 1 May.

Due to yasumi is based on arithmetic calendar, not sure this is idea for yasumi, also, it requires some local culture knowledge to implement  it

**Comment by stelgenhof** [comment]
There are indeed some countries that have holidays which aren't easy to implement (as you said: not arithmetic). Since Yasumi doesn't use any database, it is an option to capture the holidays within the code; although not ideal. 

Recently South Korea was added, and it included a holiday where predefined dates are included in the source code. As said, in some cases this maybe the only alternative. Even if the holidays only change once a year, that is still fine.

**Comment by Dagolin** [comment]
Totally agree, I found that South Korea was added with only few holidays which can be predefined. I believe that there are more which cannot be calculated before, and hard to predict, just like the golden week of the emperor's accession in Japan in 2019.

I would love to help to improve holidays of Taiwan for the predictable holidays

**Comment by stelgenhof** [comment]
If you like to give it a try, please go ahead. I would indeed first start with those holidays that are predictable (i.e. can be calculated).
