### ISSUE TITLE
Common translation

### ISSUE THREAD

**Issue by Furgas** [azuyalabs/yasumi#5]
I'm adding Polish provider, and I think that it would be nice to have some global translation table in form of shortName => [locale => transaltion, locale => translation, ...] that will be used if no translation is provided in Holiday constructor.
What do you think?

**Comment by stelgenhof** [comment]
Absolutely! Since Yasumi is in it's early stage, I decided first to put in the constructor. However that's not really flexible :). Let me think about how to do the translations.

**Comment by stelgenhof** [comment]
@Furgas I have been looking into the translation and there are some considerations here. First of all, since holidays are loaded dynamically, it would mean translations have to be reloaded if a new holiday (with its translations) is added. That might not benefit performance, also because currently you can add holidays at runtime. One way to avoid that is to disable the adding of holidays runtime (i.e. make 'addHoliday' not a public method).

Secondly, the structure of the translation files. We can have all translations in a single file representing a locale, or a single file per holiday containing all translations of one or more locales. I tend to have a single locale file (e.g. 'en_US', 'de_DE') for translation purposes (when a translator is doing one language). However, performance could be an issue here as well as all files need to be processed.

What do you think.?
