### ISSUE TITLE
Repentance Day should be official in Germany/Saxony

### ISSUE THREAD

**Issue by scrobbleme** [azuyalabs/yasumi#63]
Repentance Day  is an official holidy in Germany/Saxony, but listet as "Others" within Yasumi

http://www.officeholidays.com/countries/germany/regional.php?list_year=2017&region_code=SN

**Comment by stelgenhof** [comment]
Yes, the type "Others" is indeed not quite right for official regional holidays. The reason for choosing "Other" was probably because the other types didn't fit the classification.

Actually, the main classification "National" (within Yasumi) is then not appropriate in this regards. I think changing that name to "Official" might be a better wording. However that would require a change to all holiday providers. Which I think may be the correct way :)

For the moment, you can adjust it yourself by changing the type to "NATIONAL" if you like. Let me see if I can resolve this by changing "NATIONAL" to "OFFICIAL" or something like that.

**Comment by stelgenhof** [comment]
Created branch 'official' where the name change from NATIONAL to OFFICIAL is done.

**Comment by stelgenhof** [comment]
Issue has been resolved in the master branch. Will be included in the upcoming v1.7.0 release.
